////  Day 2 ////

//// data types stras ////

//  In the previous section, we mentioned a little bit about data types. Data or values have data types. Data types describe the characteristics of data. Data types can be divided into two :

// 1. Primitive data types
// 2. Non-primitive data types (Object References)
 
///  1.Primitive  data types 

// Primitive data types in Javascript include :
// 1. Booleans -> true or false valus
// 2. BigInt -> 
// 3. Numbers -> Integers, floats
// 4. Null -> empty value or no value
// 5. Strings -> Any data under single quote , double quote or backtick quoute 
// 6. Sumbol -> a unique balue that can be generated by Symbol constructor 
// 7. Undefined -> a declared variable without a balue

// 2. Non-primitive data types in JavaScript includes:
// 1. Objects
// 2. Arrays

// Now, let us see what exactly primitive and non-primitive data types mean. Primitive data types are immutable(non-modifiable) data types. Once a primitive data type is created we cannot modify it.


//  Primitive data types Example:
let word = 'Javascript' // If we try to modify the string stored in variable word, JavaScript should raise an error. Any data type under a single quote, double quote, or backtick quote is a string data type. 
word[0] = 'Y' 
//This expression does not change the string stored in the variable word. So, we can say that strings are not modifiable or in other words immutable. Primitive data types are compared by its values. Let us compare different data values. See the example below:

let numOne = 3;
let numTwo = 3;
console.log(numOne == numTwo); // true

let js = 'JavaScript';
let py = 'Python';
console.log( js == py ) ; // false 

let lightOn = true;
let lightOff = false;
console.log(lightOn == lightOff); // false

// 2. Non-Primitive Data Types Example :

// Array 

let nums = [1,2,3];
nums[0] = 10 ;
console.log(nums) // [10,2,3]
 
Example Array 2 :
let nums = [1,2,3];
let numbers = [1,2,3];
console.log( nums ==  numbers ); // false 

// Example Object 1 :

let userOne = {
    name : 'Sakib',
    role: 'student',
    country: 'Bangladesh'
}
let userTwo = {
    name:'Hasan',
    role:'student',
    country:'Bangladesh'
}
console.log( userOne == userTwo ) // false

// Example Object 2 : 

let nums = [1,2,3];
let numbers = nums;
console.log(nums == numbers); // true

let userOne = {
    name:'Sakib',
    role:'student',
    country:'Bangladesh'
}
let userTwo = userOne 
console.log(userOne == userTwo); // true

// 1. Numbers
// Declaring Number Data Types  Example :

let  age = 18 ;
const gravity = 9.81 ; // we use const for non-changing valuse , gravitational constant in m/s2
let mass = 72; //mass ik kilogram
const PI = 3.14;// pi a geometrical constant

// // Mpre Example 
const bollingPoint = 100;//Tempatature in oC, boiling point of water which is a constant 
const bodyTemp = 37 ;// oC average  human body temperature, which is a constant
console.log(age,gravity,mass, PI,bollingPoint,bodyTemp);

// Math Object Example 

const PI = Math.PI;
console.log(PI)  // 3.141592653589793

// Rounding to the closest number 
// if above . 5 up  if less 0.5 down rounding
console.log(Math.round(PI)); // 3 to round values to the nearest number
console.log(Math.round(9.81)); // 10 
console.log(Math.floor(PI)); //  3 rounding down  
console.log(Math.ceil(PI)); //  4 rounding  up
console.log(Math.min(-5,3,20,4,5,10)); //  4 rounding  up



 





//// data types End ////

